language: python
python:
  - "3.7"
env:
  - PYTHONPATH=$PWD/src
install:
  - pip install -r ./src/requirements.txt

script:
  - coverage run -m pytest ./src/tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
